Add pay processign through Cashew
hiqdev/yii2-merchant pull request #9
Opened 2020-10-08 12:38 UTC by tafid

2020-10-08 13:15 UTC, SilverFire requested changes

2020-10-08 13:15 UTC, SilverFire commented on src/Module.php
> +    public bool $cashewOnly = false;
`php > 7.4` в composer.json

2020-10-08 13:15 UTC, SilverFire commented on src/views/pay/deposit.php
> +        'src' => $requests['cashew_usd']->form->getRedirectUrl(), // TODO: refactor instead of hardcore
В ответе может не быть `cashew` в случае, если не получится создать запрос на оплату. Ты это видел у себя на двеве. Это нужно обработать

2020-10-08 13:15 UTC, SilverFire commented on src/views/pay/deposit.php
> +        'src' => $requests['cashew_usd']->form->getRedirectUrl(), // TODO: refactor instead of hardcore
Валюта может быть не только `usd`

2020-10-08 13:32 UTC, tafid commented on src/views/pay/deposit.php
> +        'src' => $requests['cashew_usd']->form->getRedirectUrl(), // TODO: refactor instead of hardcore
обсудили

2020-10-08 13:36 UTC, hiqsol approved these changes

2020-10-13 12:37 UTC, hiqsol approved these changes

2020-10-13 12:37 UTC, merged